export const DRINKS = [
  { id: 1,  name: 'Beer (pint)',          icon: '🍺', units: 2.3, category: 'Beer' },
  { id: 2,  name: 'Beer (half)',          icon: '🍺', units: 1.1, category: 'Beer' },
  { id: 3,  name: 'Beer (bottle 330ml)', icon: '🍺', units: 1.5, category: 'Beer' },
  { id: 4,  name: 'Beer (bottle 660ml)', icon: '🍺', units: 3.0, category: 'Beer' },
  { id: 5,  name: 'Beer (can)',           icon: '🍺', units: 1.7, category: 'Beer' },
  { id: 6,  name: 'Cider (pint)',         icon: '🍏', units: 2.3, category: 'Cider' },
  { id: 7,  name: 'Cider (half)',         icon: '🍏', units: 1.1, category: 'Cider' },
  { id: 8,  name: 'Cider (bottle)',       icon: '🍏', units: 1.5, category: 'Cider' },
  { id: 9,  name: 'Cider (can)',          icon: '🍏', units: 1.7, category: 'Cider' },
  { id: 10, name: 'Wine (glass)',         icon: '🍷', units: 2.1, category: null },
  { id: 11, name: 'Spirit + Mixer',      icon: '🥃', units: 1.0, category: null },
  { id: 12, name: 'Shot',                icon: '🥃', units: 1.0, category: null },
  { id: 13, name: 'Cocktail',            icon: '🍸', units: 1.5, category: null },
  { id: 14, name: 'Hard Seltzer (can)',  icon: '🧃', units: 1.4, category: null },
  { id: 15, name: "Wright's Gin (150ml)", icon: '🍸', units: 6.0, category: null },
  { id: 16, name: 'Alcopop (WKD/bottle)', icon: '🍹', units: 1.1, category: null },
  { id: 17, name: 'Prosecco (glass)',     icon: '🥂', units: 1.4, category: null },
  { id: 18, name: "Pimm's (glass)",       icon: '🍹', units: 1.0, category: null },
]
